### ISSUE TITLE
Feature: Infinite loop?

### ISSUE THREAD

**Issue by marcusbrose** [kenwheeler/nuka-carousel#87]

**Comment by welljs** [comment]
+1

**Comment by Lukavyi** [comment]
+1

**Comment by kenwheeler** [comment]
Almost there. Within the week.

**Comment by kenwheeler** [comment]
Done on master, release pending

**Comment by Lukavyi** [comment]
Doesn't seem to be infinite

**Comment by bvasko** [comment]
You need to set wrapAround to true in your props

**Comment by travisdmathis** [comment]
@bvasko not the same as an infinite loop.. wrapAround does not solve this problem.
